// Dados mock para produtos de embalagens
export const mockProducts = [
  {
    id: 1,
    name: 'Caixa de Papelão Ondulado 20x15x10',
    category: 'Caixas de Papelão',
    description: 'Caixa de papelão ondulado resistente, ideal para envios',
    price: 2.50,
    stock: 150,
    image: 'https://via.placeholder.com/300x300?text=Caixa+Papelao',
    material: 'Papelão Ondulado',
    size: '20x15x10 cm',
    weight: '200g',
  },
  {
    id: 2,
    name: 'Caixa de Papelão Ondulado 30x20x15',
    category: 'Caixas de Papelão',
    description: 'Caixa maior para produtos maiores',
    price: 4.20,
    stock: 120,
    image: 'https://via.placeholder.com/300x300?text=Caixa+Grande',
    material: 'Papelão Ondulado',
    size: '30x20x15 cm',
    weight: '350g',
  },
  {
    id: 3,
    name: 'Sacola Kraft com Alça 25x35',
    category: 'Sacolas',
    description: 'Sacola kraft ecológica com alça reforçada',
    price: 0.85,
    stock: 500,
    image: 'https://via.placeholder.com/300x300?text=Sacola+Kraft',
    material: 'Papel Kraft',
    size: '25x35 cm',
    weight: '80g',
  },
  {
    id: 4,
    name: 'Sacola Plástica Transparente 30x40',
    category: 'Sacolas',
    description: 'Sacola plástica transparente com alça',
    price: 0.45,
    stock: 800,
    image: 'https://via.placeholder.com/300x300?text=Sacola+Plastica',
    material: 'Plástico PEBD',
    size: '30x40 cm',
    weight: '50g',
  },
  {
    id: 5,
    name: 'Embalagem Plástica Bolha 10m',
    category: 'Embalagens Plásticas',
    description: 'Plástico bolha para proteção de produtos frágeis',
    price: 15.00,
    stock: 80,
    image: 'https://via.placeholder.com/300x300?text=Plastico+Bolha',
    material: 'Plástico com Bolhas',
    size: '10m x 1.2m',
    weight: '500g',
  },
  {
    id: 6,
    name: 'Filme Plástico Transparente 500m',
    category: 'Embalagens Plásticas',
    description: 'Filme plástico para embrulho e proteção',
    price: 12.50,
    stock: 100,
    image: 'https://via.placeholder.com/300x300?text=Filme+Plastico',
    material: 'Plástico PVC',
    size: '500m x 50cm',
    weight: '800g',
  },
  {
    id: 7,
    name: 'Pote Plástico Transparente 500ml',
    category: 'Embalagens para Alimentos',
    description: 'Pote plástico com tampa para alimentos',
    price: 0.65,
    stock: 600,
    image: 'https://via.placeholder.com/300x300?text=Pote+Plastico',
    material: 'Plástico PP',
    size: '500ml',
    weight: '45g',
  },
  {
    id: 8,
    name: 'Pote Plástico Transparente 1L',
    category: 'Embalagens para Alimentos',
    description: 'Pote plástico com tampa para alimentos maiores',
    price: 0.95,
    stock: 450,
    image: 'https://via.placeholder.com/300x300?text=Pote+1L',
    material: 'Plástico PP',
    size: '1L',
    weight: '70g',
  },
  {
    id: 9,
    name: 'Bandeja de Papelão 30x20',
    category: 'Embalagens para Alimentos',
    description: 'Bandeja de papelão para alimentos',
    price: 1.20,
    stock: 300,
    image: 'https://via.placeholder.com/300x300?text=Bandeja',
    material: 'Papelão',
    size: '30x20 cm',
    weight: '120g',
  },
  {
    id: 10,
    name: 'Etiqueta Adesiva 10x5',
    category: 'Acessórios',
    description: 'Etiqueta adesiva para identificação de produtos',
    price: 0.15,
    stock: 2000,
    image: 'https://via.placeholder.com/300x300?text=Etiqueta',
    material: 'Papel Adesivo',
    size: '10x5 cm',
    weight: '5g',
  },
  {
    id: 11,
    name: 'Fita Adesiva Marrom 48mm',
    category: 'Acessórios',
    description: 'Fita adesiva para fechamento de caixas',
    price: 3.50,
    stock: 250,
    image: 'https://via.placeholder.com/300x300?text=Fita+Adesiva',
    material: 'Polipropileno',
    size: '48mm x 50m',
    weight: '200g',
  },
  {
    id: 12,
    name: 'Papel de Seda Branco 75x100',
    category: 'Acessórios',
    description: 'Papel de seda para embrulho e proteção',
    price: 0.35,
    stock: 1000,
    image: 'https://via.placeholder.com/300x300?text=Papel+Seda',
    material: 'Papel de Seda',
    size: '75x100 cm',
    weight: '10g',
  },
];

export const categories = [
  'Caixas de Papelão',
  'Sacolas',
  'Embalagens Plásticas',
  'Embalagens para Alimentos',
  'Acessórios',
];

export const materials = [
  'Papelão Ondulado',
  'Papel Kraft',
  'Plástico PEBD',
  'Plástico com Bolhas',
  'Plástico PVC',
  'Plástico PP',
  'Papel Adesivo',
  'Polipropileno',
  'Papel de Seda',
];
